# Generated by Django 5.1.6 on 2025-03-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_rename_categories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
